name: healthque_wear_os
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  wear_os_plugin: ^0.3.0
  freezed_annotation: ^3.0.0
  freezed: ^3.0.4
  google_sign_in: ^6.3.0
  intl_utils: ^2.8.10
  intl: ^0.19.0
  go_router: ^14.8.1
  flutter_localization: ^0.3.1
  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.70.2
  get_it: ^8.0.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  gap: ^3.0.1
  firebase_database: ^11.3.5
  flutter_local_notifications: ^18.0.1
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: en
  arb_dir: lib/core/localization
  output_dir: lib/core/localization/generated

dependency_overrides:
  source_gen: ^2.0.0